channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=24.0
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - numpy==1.25.2
  - tensorflow-macos==2.15.0
  - tensorflow==2.15.0
name: mlflow-env
